hostIP: 192.168.50.5 

# will set your admin password for the web inteface
adminPassword: ""

# will create kubernees ingress
ingress:
  enabled: true
  hosts:
  - pihole
  - pihole.local
  - pi.hole

# will create kubernetes services for web admin
serviceWeb:
  loadBalancerIP: {{ tpl .Values.hostIP . }}
  type: ClusterIP
  
# create a kubernetes service and expose
# port 53 outside of cluster on the local network
serviceDns:
  loadBalancerIP: {{ tpl .Values.hostIP . }}
  type: LoadBalancer
  
# enables cloudflare tunnel sidecar container
# and sets upstream dns in pihole to leverage it
doh:
  enabled: true
  pullPolicy: Always
  envVars: {
    DOH_UPSTREAM: "https://1.1.1.1/dns-query"
  }
  
persistentVolumeClaim:
  enabled: true
  existingClaim: pihole-config
