apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-config
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/k3s/pihole/config"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pihole-config
spec:
  volumeName: pihole-config
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
