apiVersion: v1
kind: PersistentVolume
metadata:
  name: mqtt-data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/k3s/mqtt/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mqtt-config
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/k3s/mqtt/config"
